import {
  TypingAnimationElement,
  ClippedText,
  ClearFix,
  Container,
  FlexContainer,
  FlexItem,
  DivV,
  RespImg,
  RespVideo,
  RespGrid,
  UnstyledList,
  NavUl,
  RespHeading,
  RespP,
  Circle,
  RespBackgImg,
} from "./parts/custom-comp.jsx";
import styles from "./parts/styles.js";
import {
  useActive,
  useHover,
  useMediaQuery,
  useMediaStyle,
  useMousePosition,
} from "./parts/custom-hooks.jsx";

import {
  mergeStyles,
  mergeRefs,
  activeStyle,
  hoverStyle,
} from "./parts/custom-func.jsx";

export {
  ClearFix,
  Container,
  FlexContainer,
  FlexItem,
  DivV,
  RespImg,
  RespVideo,
  RespGrid,
  UnstyledList,
  NavUl,
  RespHeading,
  RespP,
  Circle,
  RespBackgImg,
  useActive,
  useHover,
  useMediaQuery,
  useMediaStyle,
  mergeRefs,
  styles,
  hoverStyle,
  activeStyle,
  useMousePosition,
  TypingAnimationElement,
  ClippedText,
  mergeStyles,
};
